development:
  adapter: postgresql
  encoding: unicode
  database: whub_dev
  pool: 5
  username: rails
  password: '!QAZxsw2#EDC'

test:
  adapter: postgresql
  encoding: unicode
  database: whub_test
  pool: 5
  username: rails
  password: '!QAZxsw2#EDC'

production:
  adapter: postgresql
  encoding: unicode
  database: whub
  pool: 5
  username: rails
  password: '!QAZxsw2#EDC'
